language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: nightly

sudo: false
